# For more on configuring pre-commit hooks (see https://pre-commit.com/)

# TODO: remove global exclusion of tests when testing overhaul is complete
exclude: "^tests/.*|^project_example/.*|^scripts/.*|^envs/.*|^.github/.*"


default_language_version:
  python: python3.8

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-yaml
    args: [--unsafe]
  - id: check-json
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args:
    - "--line-length=99"
    - "--target-version=py38"
  - id: black
    alias: black-check
    stages: [manual]
    args:
    - "--line-length=99"
    - "--target-version=py38"
    - "--check"
    - "--diff"
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: flake8
    args: ['--ignore=E203,W503'] # see https://github.com/psf/black/issues/315 https://github.com/psf/black/issues/52
    alias: flake8-check
    stages: [manual]
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.280
  hooks:
  - id: pyright
